### PR TITLE
packaging of new upstream version 1.6.0

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
Hi Bernd,

I ported the new upstream release to Debian. There are a number of tags (gpsbabel_1_6_0, upstream/1.6.0+ds). Can you pull them from my fork one this got accepted (as well as the upstream branch)? Are you willing to move this over to salsa.d.o? I would be happy to join as a maintainer.

Cheers Jochen

**Comment by bzed** [comment]
@jspricke thanks for your work, please give me some days to get it all sorted! Moving to salsa is a good idea, too!

**Comment by bzed** [comment]
Hi @jspricke, could you just ush your changes to https://salsa.debian.org/debian-gps-team/pkg-gpsbabel ? You should have permissions to do so :)

**Comment by jspricke** [comment]
Done, thx!

**Pull request closed without merging**
